# Generated by Django 3.2.4 on 2021-12-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_expense_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='balane',
            new_name='balance',
        ),
    ]
