# Generated by Django 3.2.4 on 2021-12-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_balane_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
